# Options for dump_restbase script
dump_restbase:
  workDir: /tmp
  dumpDir: /tmp

# Options for dump_wiki script
dump_wiki:
  domain: en.wikipedia.org
  ns: 0
  apiURL: http://en.wikipedia.org/w/api.php
  d: /tmp

# Global options
global_opts:
  # Article dump parallelism
  maxConcurrency : 50
  concurrency: 3
